---
- hosts: tag_class_kubernetes
  # TODO: try this with gather_facts: yes
  gather_facts: no
  tasks:
    - name: gather ec2 facts
      local_action: ec2_facts
    - name: terminate instances
      local_action: ec2
        region="{{ region }}"
        wait=yes
        instance_ids="{{ hostvars[inventory_hostname]['ec2_id'] }}"
        state=absent

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: delete key pair
      ec2_key:
        region: "{{ region }}"
        name: "{{ resource_name }}"
        state: absent
    - name: delete local key pair file
      file:
        path: "~/.ssh/{{ resource_name }}.pem"
        state: absent
    - name: delete security group
      ec2_group:
        region: "{{ region }}"
        name: "{{ resource_name }}"
        description: "Security Group for Kubernetes"
        state: absent
    - name: delete local kubeadm.yaml file
      file:
        path: "{{ kubeadm_file }}"
        state: absent
    - name: delete local controller.yaml file
      file:
        path: "{{ controller_file }}"
        state: absent
