---
- name: common tasks
  hosts: tag_class_kubernetes
  gather_facts: no
  become: yes
  roles:
    - common
- name: install kubeadm
  hosts: tag_class_kubernetes
  become: yes
  roles:
    - kubeadm
- name: init controller
  hosts: tag_role_controller
  roles:
    - controller
- name: join workers
  hosts: tag_role_worker
  become: yes
  roles:
    - worker
